### PR TITLE
ProcessExtensions: ensure we capture all child Process output

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/redhat-developer/dotnet-bunny/issues/35

@omajid @RheaAyase ptal

### CODE REVIEW

**Comment by RheaAyase** [comment]
lgtm

**Comment by omajid** [comment]
I think we should merge this (even though I haven't had the time to do a proper review)

**Comment by RheaAyase** [comment]
Right, this got closed when I changed master to main

**Comment by RheaAyase** [comment]
Merged.

**Comment by omajid** [comment]
Thanks, @tmds for finding and fixing this!

**Pull request closed without merging**
