### PR TITLE
Add support for skipping tests using traits.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/redhat-developer/dotnet-bunny/issues/62.
Fixes https://github.com/redhat-developer/dotnet-bunny/issues/67.

@omajid ptal.

### CODE REVIEW

**Comment by omajid** [comment]
Thanks for the PR! I will try to review it soon.

**Comment by tmds** [comment]
@omajid ptal.

**Comment by tmds** [comment]
> Can you help me understand how you plan to use this to support https://github.com/redhat-developer/dotnet-regular-tests/issues/235 ?

For example, we have a trait named `tarball`. When running tests against a .NET tarball (like in a vmr CI job), we add `--trait tarball` to the bunny commandline. Any tests that are known to fail when run against the tarball are marked with `skipWhen: "tarball"`.

**Comment by omajid** [comment]
Thanks!

**Pull request merged**
